# -*- coding: utf-8 -*-
"""faceRecognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HmJuoQzbRenxNGlMbuVcL-decKIDIDFm
"""



import face_align as face_align
import onnx
import onnxruntime
import os
import pickle
import numpy as np
from PIL import Image
from typing import List
from tqdm import tqdm
import insightface
from sklearn.neighbors import NearestNeighbors
import cv2
from SCRFD import SCRFD
from ArcFace import ArcFaceONNX
import time

"""<h1> install buffalo_l model </h1>
<a>'det_10g.onnx': detection </a> <br/>
<c>'w600k_r50.onnx': </c> 
"""

def plot_one_box(x, img, color=None, label=None, line_thickness=None):
    # Plots one bounding box on image img
    tl = line_thickness or round(0.002 * (img.shape[0] + img.shape[1]) / 2) + 1  # line/font thickness
    c1, c2 = (int(x[0]), int(x[1])), (int(x[2]), int(x[3]))
    cv2.rectangle(img, c1, c2, color, thickness=tl, lineType=cv2.LINE_AA)
    if label:
        tf = max(tl - 1, 1)  # font thickness
        t_size = cv2.getTextSize(label, 0, fontScale=tl / 3, thickness=tf)[0]
        c2 = c1[0] + t_size[0], c1[1] - t_size[1] - 3
        cv2.rectangle(img, c1, c2, color, -1, cv2.LINE_AA)  # filled
        cv2.putText(img, label, (c1[0], c1[1] - 2), 0, tl / 3, [225, 255, 255], thickness=tf, lineType=cv2.LINE_AA)



def Area(rect):
  return (rect[2] - rect[0]) * (rect[3] - rect[1])




def resize_img(img, scale_percent):
    width = int(img.shape[1] * scale_percent / 100)
    height = int(img.shape[0] * scale_percent / 100)
    dim = (width, height)
      
    # resize image
    resized = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
    return resized
#ham tao embeeding cua 1 anh --> tra ve 1 list embeeding va 1 list label
def generate_embs(img_fpaths: List[str], app, detector, label, path): 
    embs_set = list()
    embs_label = list()

    for img_fpath in img_fpaths:  
       #read image
        img = cv2.imread(os.path.join(path, img_fpath))
        if img is None:
          print(f'{img_fpath} of number {label} Error. No image found. Skip')

        boxs, kpss = detector.autodetect(img)

        if len(kpss) == 0:
          print(f'{img_fpath} of number {label} Error. No face spotted. Skip')
          continue
      #  # generate Insightface embedding
        if len(kpss) > 1: #choose the largest one
          kpss = [x for _,x in sorted(zip(boxs, kpss), key = lambda e: -Area(e[0]))]
        try:
          emb_res = app.get(img, kpss[0])         
          embs_set.append(emb_res)          
          embs_label.append(label)
        except:
          print(f'\nno embedding found for this image: {img_fpath} of number {label}')         

    return embs_set, embs_label


"""<h1> test function, don't run this c
ell <h1>
"""



from sklearn.model_selection import train_test_split

def generate_train_and_test(path_dir):
  train, test = train_test_split(path_dir)
  return train, test



"""Evaluating metrics - **p_at_k**"""

# p@k
def p_at_k(probe_embs, probe_labels, labels, inds, k=1):
  p_at_k = np.zeros(len(probe_embs))
  for i in range(len(probe_embs)):
      true_label = probe_labels[i]
      pred_neighbr_idx = inds[i]
      
      pred_labels = [labels[id] for id in pred_neighbr_idx]
      pred_is_labels = [1 if label == true_label else 0 for label in pred_labels]
      
      p_at_k[i] = np.mean(pred_is_labels)
      
  p_at_k.mean()



